export interface MovieData {
    id: number,
    title?: string,
    year?: string,
    genre?: string[],
    rating?: string,
    director?: string,
    actors?: string[],
    plot?: string,
    poster?: string,
    cover_img?: string,
    runtime?: string,
    awards?: string,
    language?: string[],
    boxoffice?: string,
    production?: string[],
    certified?: string,
    type?: string,
}